#ifndef LINECALCULATION_H
#define LINECALCULATION_H

#include "abstractlinedata.h"
#include "textdataunit.h"

namespace post3dapp{

enum class CalculationStatus{None,
                            Skip,
                            OutgroupP,
                            OutgroupS,
                            Cover,
                            Organize,
                            Outline,
                            Plan,
                            Section,
                            Lsgir,
                            Lscol,
                            Lswal,
                            Lsswa,
                            Lsfwa,
                            Lsbra,
                            Lsbeam,
                            Lsslab,
                            Lsopen,
                            Lsbs,
                            Lsbsrc,
                            Lsdamp,
                            Lsmen,
                            Alist,
                            Calc,
                            Stnd,
                            Policy,
                            Stt,
                            Matc,
                            Matr,
                            Mats,
                            Ccs,
                            Policyld,
                            Ldl,
                            Ldf,
                            Ldm,
                            Ldj,
                            Snow,
                            Wind,
                            Other,
                            Lplan,
                            Seisle,
                            Lcmqp,
                            Lcmqs,
                            Jmassp,
                            Jmasss,
                            Estim,
                            Policyec,
                            Cmodel,
                            Emodel,
                            ModelP,
                            ModelS,
                            MphaiP,
                            MphaiS,
                            MrlP,
                            MrlS,
                            MclP,
                            MclS,
                            MblP,
                            MblS,
                            Anacon,
                            Rfloor,
                            Jspring,
                            Mspring,
                            Mdetail,
                            Autophai,
                            Autolk,
                            Jnt,
                            Index,
                            Frame,
                            Pnlmdl,
                            Outcs,
                            VjstrP,
                            VjstrS,
                            VfstrP,
                            VfstrS,
                            Hratio,
                            HjstrP,
                            HjstrS,
                            HfstrP,
                            HfstrS,
                            Crez,
                            React,
                            Ststiff,
                            Frstiff,
                            Frdist,
                            Qmap,
                            Policych,
                            Chcase,
                            ChvP,
                            ChvS,
                            ChhP,
                            ChhS,
                            Chlistm,
                            Chlistq,
                            Chcol,
                            Chgir,
                            Chwal,
                            Chbra,
                            Chopen,
                            Chps2,
                            Chprc2,
                            Chpsrc2,
                            Chpcft2,
                            Chps3,
                            Chprc3,
                            Chpsrc3,
                            Chpcft3,
                            Chsrcbase,
                            Chsbase,
                            Chneobase,
                            Chnewbase,
                            Chbpbase,
                            Chcutoff,
                            Chbondl1,
                            Chbonds1,
                            Chbonds2,
                            Policyf,
                            Policystec,
                            Mxdfrm,
                            Prestec,
                            Gckcp,
                            Stecf,
                            Cwarea,
                            Cgcmp1,
                            Policyquds,
                            Quds,
                            QudsCase,
                            QudsFloor,
                            QudsGrid,
                            Seislp,
                            Policypc,
                             Pmodel,
                             Dspush,
                             Dsgene,
                             Dsstep,
                             Dscurve,
                             Dsstr,
                             Dscond,
                             Mrnk,
                             Rncs,
                             Rncrc,
                             Rncsrc,
                             Rnccft,
                             Rngs,
                             Rngrc,
                             Rngsrc,
                             Rnvs,
                             Rnwrc,
                             Rnwsrc,
                             Rnprc,
                             Qun,
                             Grbend,
                             Grbondi,
                             Grbondp,
                             Yokohogou,
                             Dssh,
                             Dsmu,
                             Qupush,
                             Qugene,
                             Qustep,
                             Qucurve,
                             Qucond,
                             Qudetrm,
                             Qustr,
                             Qucrc,
                             Qucsrc,
                             Qugrc,
                             Qugsrc,
                             Quwrc,
                             Quwsrc,
                             Qups,
                             Quprc,
                             Qupsrc,
                             Qupcft,
                             Qush,
                             Dsqucurve,
                             Quneed,
                             Quneedf,
                             Cgcmpm,
                             Cgcmpf,
                             Mbcpr,
                             Qbcpr,
                             Mult,
                             Programe,
                             Message,
                             Opinionc,
                             Opinion,
                             Contents,
                             Contents2,
                             End
                            };

class LineCalculation : public AbstractLineData
{
public:
    explicit LineCalculation(const QString& _key = QString{},
                             CalculationStatus _status = CalculationStatus::None,
                             const QList<TextDataUnit>& _unit = QList<TextDataUnit>(),
                             const QList<CalculationStatus>& _premiseStatus = QList<CalculationStatus>())
        : AbstractLineData(_key, _unit), myStatus(_status), premiseStatus(_premiseStatus){};
    CalculationStatus getStatus() const{return myStatus;}
    bool MatchKeyword(CalculationStatus, const QString&);
private:
    const CalculationStatus myStatus;
    const QList<CalculationStatus> premiseStatus;
};
} // namespace post3dapp

#endif // LINECALCULATION_H
