#include <QtGui>
#include <QtWidgets>
#include <QAbstractTableModel>
#include <QAction>
#include <QBoxLayout>
#include <QBrush>
#include <QButtonGroup>
#include <QCheckBox>
#include <QComboBox>
#include <QDateTime>
#include <QDesktopServices>
#include <QDialog>
#include <QDialogButtonBox>
#include <QDoubleValidator>
#include <QFileDialog>
#include <QFontMetrics>
#include <QFontMetricsF>
#include <QFrame>
#include <QGraphicsItem>
#include <QGraphicsLineItem>
#include <QGraphicsView>
#include <QHBoxLayout>
#include <QHeaderView>
#include <QIcon>
#include <QLabel>
#include <QLayout>
#include <QLineEdit>
#include <QMdiArea>
#include <QMenu>
#include <QMessageBox>
#include <QModelIndex>
#include <QMouseEvent>
#include <QPainter>
#include <QPaintEvent>
#include <QPlainTextEdit>
#include <QPointF>
#include <QPrintDialog>
#include <QPrinter>
#include <QPrintPreviewWidget>
#include <QProgressDialog>
#include <QProxyStyle>
#include <QPushButton>
#include <QRadioButton>
#include <QRectF>
#include <QResource>
#include <QScrollArea>
#include <QScrollBar>
#include <QSortFilterProxyModel>
#include <QSizePolicy>
#include <QSlider>
#include <QSpinBox>
#include <QSplashScreen>
#include <QSplitter>
#include <QStatusBar>
#include <QStackedWidget>
#include <QStyledItemDelegate>
#include <QTimer>
#include <QTableView>
#include <QTabWidget>
#include <QTextBlock>
#include <QToolTip>
#include <QToolButton>
#include <QUndoCommand>
#include <QUndoStack>
#include <QUrl>
#include <QUuid>
#include <QVBoxLayout>
#include <QWheelEvent>
#include <QWidget>

#include <QCoreApplication>
#include <QApplication>
#include <QColor>
#include <QDebug>
#include <QString>
#include <QStringList>
#include <QFile>
#include <QFileInfo>
#include <QDir>
#include <QHash>
#include <QMap>
#include <QTextCodec>
#include <QTextStream>
#include <QVariant>
#include <QVector>
