#include "define_defaultvalue.h"

namespace post3dapp{

const QMap<QString, REGULATION> REGULATION::defaultFloor = QMap<QString, REGULATION>{
    {u8"NO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"NAME", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"HEIGHT", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"FLOORSCALE", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"表示する"))},
    {u8"BEAM", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"SLAB", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"UUID", REGULATION(TABLEDATATYPE::TB_STRING)}
};

const QStringList REGULATION::defaultFloorScale = QList<QString>{u8"表示する", u8"表示しない"};

const QMap<QString, REGULATION> REGULATION::defaultAnalysisFloor = QMap<QString, REGULATION>{
    {u8"NO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FLOOR", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"LEVEL", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"CHILDFLOOR", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"一般階"))},
    {u8"PARENTFLOOR", REGULATION(TABLEDATATYPE::TB_STRING)}
};
const QStringList REGULATION::defaultAnalysisFloorChildFloor = QList<QString>{u8"一般階", u8"補助階"};

const QMap<QString, REGULATION> REGULATION::defaultFrameGroup = QMap<QString, REGULATION>{
    {u8"NO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FRAMEGROUP", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FRAMETYPE", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FRAMESUM", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"OX", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"OY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"STARTANGLE", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"ENDANGLE", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(180.0))},
    {u8"DIVISIONS", REGULATION(TABLEDATATYPE::TB_INT, QVariant(20))},
    {u8"LENGTHPLUS", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(50.0))},
    {u8"LENGTHMINUS", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(10.0))},
    {u8"FLOORFROM", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FLOORTO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"GID", REGULATION(TABLEDATATYPE::TB_STRING)},
};
const QStringList REGULATION::defaultFrameGroupFrameType = QList<QString>{u8"直線", u8"円周", u8"半径", u8"直径", u8"任意点列", u8"閉じた円", u8"閉じた点列"};

const QMap<QString, REGULATION> REGULATION::defaultFrameSubGroup = QMap<QString, REGULATION>{
    {u8"NO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FRAMEGROUP", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FRAMETYPE", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"NAME", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"SPAN", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"ANGLE", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"BUTTON", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"XYPOINTS", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"GID", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"UUID", REGULATION(TABLEDATATYPE::TB_STRING)}
};

const QMap<QString, REGULATION> REGULATION::defaultFrameXY = QMap<QString, REGULATION>{
    {u8"NO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"X", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"Y", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))}
};

const QMap<QString, REGULATION> REGULATION::defaultMaterial = {
    {u8"NO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"CATEGORY", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"LABEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"SYMBOL", REGULATION(TABLEDATATYPE::TB_STRING, QVariant("D"))},
    {u8"RANGEFROM", REGULATION(TABLEDATATYPE::TB_INT)},
    {u8"RANGETO", REGULATION(TABLEDATATYPE::TB_INT)},

    {u8"E", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"G", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"UNITWEIGHT1", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"UNITWEIGHT2", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"MODULARRATIO", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"F_STRENGTH", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"T_L", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"T_S", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"T_U", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"C_L", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"C_S", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"C_U", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"S_L", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"S_S", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"S_U", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"A_L", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"A_S", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"A_U", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"UA_L", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"UA_S", REGULATION(TABLEDATATYPE::TB_DOUBLE)},

};

const QStringList REGULATION::defaultMaterialSymbol = {
    "", "D", "E", "F", "S", "R", "U"
};

const QMap<QString, REGULATION> REGULATION::defaultColumnRc = QMap<QString, REGULATION>{
    {u8"NO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"LABEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FLOORFROM", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FLOORTO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FINISHLOAD", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"CONC", REGULATION(TABLEDATATYPE::TB_STRING)},

    {u8"iDY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iDZ", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iMAINBAR1", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"iMAINBAR2", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"iMAINBARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iAXIALCENTERY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iAXIALCENTERZ", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iAXIALDY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iAXIALDZ", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iAXIALBAR1", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"iAXIALBAR2", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"iAXIALBARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iHOOPY", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"iHOOPZ", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"iHOOPPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iHOOPPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(100))},
    {u8"iRK", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"iRY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(80.0))},

    {u8"jDY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jDZ", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jMAINBAR1", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"jMAINBAR2", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"jMAINBARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jAXIALCENTERY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jAXIALCENTERZ", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jAXIALDY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jAXIALDZ", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jAXIALBAR1", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"jAXIALBAR2", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"jAXIALBARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jHOOPY", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"jHOOPZ", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"jHOOPPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jHOOPPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(100))},
    {u8"jRK", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"jRY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(80.0))}
};

const QMap<QString, REGULATION> REGULATION::defaultColumnS = QMap<QString, REGULATION>{
    {u8"NO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"LABEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FLOORFROM", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FLOORTO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FINISHLOAD", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"iLENGTH", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"BASELIST", REGULATION(TABLEDATATYPE::TB_STRING)},

    {u8"iSTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iSHAPELISTNAME", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iSTANDARDSHAPESTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iH", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iB", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iT1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iT2", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iH_T", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iB_T", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iT1_T", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iT2_T", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},

    {u8"jSTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jSHAPELISTNAME", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jSTANDARDSHAPESTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jH", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jB", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jT1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jT2", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jH_T", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jB_T", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jT1_T", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jT2_T", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))}
};

const QStringList REGULATION::defaultColumnSSteelShape = {
    "", "WH", "WI", "WBX", "WP",
    "WT1", "WT2", "WT3", "WT4",
    "WC1", "WC2", "WC3", "WC4",
    "WPL", "WBR", "CRS", "CRH"
};


const QMap<QString, REGULATION> REGULATION::defaultColumnSrc = QMap<QString, REGULATION>{
    {u8"NO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"LABEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FLOORFROM", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FLOORTO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FINISHLOAD", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"CONC", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FILLEDCONC", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iLENGTH", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"BASELIST", REGULATION(TABLEDATATYPE::TB_STRING)},

    {u8"iDY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iDZ", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iMAINBAR1", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"iMAINBAR2", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"iMAINBARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iAXIALCENTERY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iAXIALCENTERZ", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iAXIALDY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iAXIALDZ", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iAXIALBAR1", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"iAXIALBAR2", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"iAXIALBARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iHOOPY", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"iHOOPZ", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"iHOOPPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iHOOPPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(100))},
    {u8"iRK", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"iRY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(80.0))},
    {u8"iSTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iSHAPELISTNAME", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iSTANDARDSHAPESTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iH", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iB", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iT1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iT2", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iCOODINATEY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iCOODINATEZ", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iSHAPELISTNAME_T", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iSTANDARDSHAPESTEEL_T", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iH_T", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iB_T", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iT1_T", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iT2_T", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iCOODINATEY_T", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iCOODINATEZ_T", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},

    {u8"jDY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jDZ", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jMAINBAR1", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"jMAINBAR2", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"jMAINBARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jAXIALCENTERY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jAXIALCENTERZ", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jAXIALDY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jAXIALDZ", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jAXIALBAR1", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"jAXIALBAR2", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"jAXIALBARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jHOOPY", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"jHOOPZ", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"jHOOPPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jHOOPPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(100))},
    {u8"jRK", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"jRY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(80.0))},
    {u8"jSTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jSHAPELISTNAME", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jSTANDARDSHAPESTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jH", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jB", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jT1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jT2", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jCOODINATEY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jCOODINATEZ", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jSHAPELISTNAME_T", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jSTANDARDSHAPESTEEL_T", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jH_T", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jB_T", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jT1_T", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jT2_T", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jCOODINATEY_T", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jCOODINATEZ_T", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
};

const QStringList REGULATION::defaultColumnSrcSteelShape = {
    "", "WH", "WBX", "WP", "WT1", "WT2", "WC1", "WC2", "WPL", "WBR"
};
const QStringList REGULATION::defaultColumnSrcSteelShapeT = {
    "", "WH", "WT1", "WT2", "WC1", "WC2"
};


const QMap<QString, REGULATION> REGULATION::defaultColumnCft = QMap<QString, REGULATION>{
    {u8"NO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"LABEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FLOORFROM", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FLOORTO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FINISHLOAD", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"FILLEDCONC", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iLENGTH", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"BASELIST", REGULATION(TABLEDATATYPE::TB_STRING)},

    {u8"iSTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iSHAPELISTNAME", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iSTANDARDSHAPESTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iH", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iB", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iT1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iT2", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},

    {u8"jSTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jSHAPELISTNAME", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jSTANDARDSHAPESTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jH", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jB", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jT1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jT2", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
};

const QStringList REGULATION::defaultColumnCftSteelShape = {
    "", "WBX", "WP"
};

const QMap<QString, REGULATION> REGULATION::defaultGirderRc = QMap<QString, REGULATION>{
    {u8"NO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"LABEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FLOORFROM", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FLOORTO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"CANTILEVER", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"一般"))},
    {u8"FINISHLOAD", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"CONC", REGULATION(TABLEDATATYPE::TB_STRING)},

    {u8"iDY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iDZ", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iMAINBAR1", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"iMAINBAR2", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"iMAINBARPHI1", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iMAINBARPHI2", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iHOOPZ", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"iHOOPPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iHOOPPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},
    {u8"iRK", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"iRKU", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"iRKB", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"iRY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(80.0))},

    {u8"mDY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"mDZ", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"mMAINBAR1", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"mMAINBAR2", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"mMAINBARPHI1", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"mMAINBARPHI2", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"mHOOPZ", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"mHOOPPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"mHOOPPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},
    {u8"mRK", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"mRKU", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"mRKB", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"mRY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(80.0))},

    {u8"jDY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jDZ", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jMAINBAR1", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"jMAINBAR2", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"jMAINBARPHI1", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jMAINBARPHI2", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jHOOPZ", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"jHOOPPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jHOOPPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},
    {u8"jRK", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"jRKU", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"jRKB", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"jRY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(80.0))}
};

const QStringList REGULATION::defaultGirderCantilever = {
    "", u8"一般", u8"片持"
};

const QMap<QString, REGULATION> REGULATION::defaultGirderS = {
    {u8"NO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"LABEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FLOORFROM", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FLOORTO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"CANTILEVER", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"一般"))},
    {u8"FINISHLOAD", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"iLENGTH", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"jLENGTH", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"iENDSTIFFENER", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"無し"))},
    {u8"jENDSTIFFENER", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"無し"))},

    {u8"iSTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iSTEELWEB", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iSHAPELISTNAME", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iSTANDARDSHAPESTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iH", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iB", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iT1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iT2", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},

    {u8"mSTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"mSTEELWEB", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"mSHAPELISTNAME", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"mSTANDARDSHAPESTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"mH", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"mB", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"mT1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"mT2", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},

    {u8"jSTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jSTEELWEB", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jSHAPELISTNAME", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jSTANDARDSHAPESTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jH", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jB", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jT1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jT2", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))}
};

const QStringList REGULATION::defaultGirderSSteelShape = {
    "", "WH", "WI", "WBX", "WP", "WT1", "WT2", "WT3", "WT4", "WC1", "WC2", "WC3", "WC4", "WPL", "WBR"
};
const QStringList REGULATION::defaultGirderSStiffner = {
    "", u8"無し", u8"有り"
};

const QMap<QString, REGULATION> REGULATION::defaultGirderSrc = {
    {u8"NO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"LABEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FLOORFROM", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FLOORTO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"CANTILEVER", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"一般"))},
    {u8"FINISHLOAD", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"CONC", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iLENGTH", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"jLENGTH", REGULATION(TABLEDATATYPE::TB_DOUBLE)},

    {u8"iDY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iDZ", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iMAINBAR1", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"iMAINBAR2", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"iMAINBARPHI1", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iMAINBARPHI2", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iHOOPZ", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"iHOOPPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iHOOPPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},
    {u8"iRK", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"iRKU", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"iRKB", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"iRY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(80.0))},
    {u8"iRY1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(80.0))},
    {u8"iSTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iSTEELWEB", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iSHAPELISTNAME", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iSTANDARDSHAPESTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iH", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iB", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iT1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iT2", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iCOODINATEY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iCOODINATEZ", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},

    {u8"mDY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"mDZ", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"mMAINBAR1", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"mMAINBAR2", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"mMAINBARPHI1", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"mMAINBARPHI2", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"mHOOPZ", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"mHOOPPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"mHOOPPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},
    {u8"mRK", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"mRKU", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"mRKB", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"mRY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(80.0))},
    {u8"mRY1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(80.0))},
    {u8"mSTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"mSTEELWEB", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"mSHAPELISTNAME", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"mSTANDARDSHAPESTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"mH", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"mB", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"mT1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"mT2", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"mCOODINATEY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"mCOODINATEZ", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},

    {u8"jDY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jDZ", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jMAINBAR1", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"jMAINBAR2", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"jMAINBARPHI1", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jMAINBARPHI2", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jHOOPZ", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"jHOOPPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jHOOPPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},
    {u8"jRK", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"jRKU", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"jRKB", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"jRY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(80.0))},
    {u8"jRY1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(80.0))},
    {u8"jSTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jSTEELWEB", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jSHAPELISTNAME", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jSTANDARDSHAPESTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jH", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jB", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jT1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jT2", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jCOODINATEY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jCOODINATEZ", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
};

const QStringList REGULATION::defaultGirderSrcSteelShape = {
    "", "WH", "WI", "WBX", "WP", "WT1", "WT2", "WT3", "WT4", "WC1", "WC2", "WC3", "WC4", "WPL", "WBR"
};

const QMap<QString, REGULATION> REGULATION::defaultBraceS = {
    {u8"NO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"LABEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FINISHLOAD", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"COMPRESSIVERESISTANCE", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"圧縮引張共"))},
    {u8"iLENGTH", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"jLENGTH", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"AREA", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"EFFECTIVEAREA", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"SLENDERNESSRATIO", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"UNITMASS", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"DISPLAYHEIGHT", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(200.0))},
    {u8"DISPLAYWIDTH", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(200.0))},

    {u8"iSTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iSHAPELISTNAME", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iSTANDARDSHAPESTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iH", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iB", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iT1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iT2", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},

    {u8"mSTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"mSHAPELISTNAME", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"mSTANDARDSHAPESTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"mH", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"mB", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"mT1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"mT2", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},

    {u8"jSTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jSHAPELISTNAME", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jSTANDARDSHAPESTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jH", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jB", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jT1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jT2", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
};

const QStringList REGULATION::defaultBraceSSteelShape = {
    "", "WH", "WI", "WBX", "WP", "WT1", "WT2", "WT3", "WT4", "WC1", "WC2", "WC3", "WC4", "WPL", "WBR"
};

const QStringList REGULATION::defaultBraceSCompressiveResistance = {
    "", u8"圧縮引張共", u8"引張のみ"
};

const QMap<QString, REGULATION> REGULATION::defaultBeamRc = {
    {u8"NO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"LABEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"CANTILEVER", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"一般"))},
    {u8"FINISHLOAD", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"CONC", REGULATION(TABLEDATATYPE::TB_STRING)},

    {u8"iDY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iDZ", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iMAINBAR1", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"iMAINBAR2", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"iMAINBARPHI1", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iMAINBARPHI2", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iHOOPZ", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"iHOOPPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iHOOPPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},
    {u8"iRK", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"iRKU", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"iRKB", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"iRY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(80.0))},

    {u8"mDY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"mDZ", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"mMAINBAR1", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"mMAINBAR2", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"mMAINBARPHI1", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"mMAINBARPHI2", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"mHOOPZ", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"mHOOPPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"mHOOPPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},
    {u8"mRK", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"mRKU", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"mRKB", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"mRY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(80.0))},

    {u8"jDY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jDZ", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jMAINBAR1", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"jMAINBAR2", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"jMAINBARPHI1", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jMAINBARPHI2", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jHOOPZ", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"jHOOPPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jHOOPPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},
    {u8"jRK", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"jRKU", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"jRKB", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"jRY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(80.0))}
};

const QMap<QString, REGULATION> REGULATION::defaultBeamS = {
    {u8"NO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"LABEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"CANTILEVER", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"一般"))},
    {u8"FINISHLOAD", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"iLENGTH", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"jLENGTH", REGULATION(TABLEDATATYPE::TB_DOUBLE)},

    {u8"iSTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iSTEELWEB", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iSHAPELISTNAME", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iSTANDARDSHAPESTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iH", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iB", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iT1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iT2", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},

    {u8"mSTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"mSTEELWEB", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"mSHAPELISTNAME", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"mSTANDARDSHAPESTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"mH", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"mB", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"mT1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"mT2", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},

    {u8"jSTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jSTEELWEB", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jSHAPELISTNAME", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jSTANDARDSHAPESTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jH", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jB", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jT1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jT2", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))}
};


const QStringList REGULATION::defaultBeamSSteelShape = {
    "", "WH", "WI", "WBX", "WP", "WT1", "WT2", "WT3", "WT4", "WC1", "WC2", "WC3", "WC4", "WPL", "WBR"
};

const QMap<QString, REGULATION> REGULATION::defaultBeamSrc = {
    {u8"NO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"LABEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"CANTILEVER", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"一般"))},
    {u8"FINISHLOAD", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"CONC", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iLENGTH", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"jLENGTH", REGULATION(TABLEDATATYPE::TB_DOUBLE)},

    {u8"iDY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iDZ", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iMAINBAR1", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"iMAINBAR2", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"iMAINBARPHI1", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iMAINBARPHI2", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iHOOPZ", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"iHOOPPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iHOOPPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},
    {u8"iRK", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"iRKU", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"iRKB", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"iRY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(80.0))},
    {u8"iRY1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(80.0))},
    {u8"iSTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iSTEELWEB", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iSHAPELISTNAME", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iSTANDARDSHAPESTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"iH", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iB", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iT1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iT2", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iCOODINATEY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"iCOODINATEZ", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},

    {u8"mDY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"mDZ", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"mMAINBAR1", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"mMAINBAR2", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"mMAINBARPHI1", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"mMAINBARPHI2", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"mHOOPZ", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"mHOOPPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"mHOOPPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},
    {u8"mRK", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"mRKU", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"mRKB", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"mRY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(80.0))},
    {u8"mRY1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(80.0))},
    {u8"mSTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"mSTEELWEB", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"mSHAPELISTNAME", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"mSTANDARDSHAPESTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"mH", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"mB", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"mT1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"mT2", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"mCOODINATEY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"mCOODINATEZ", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},

    {u8"jDY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jDZ", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jMAINBAR1", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"jMAINBAR2", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"0"))},
    {u8"jMAINBARPHI1", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jMAINBARPHI2", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jHOOPZ", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"jHOOPPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jHOOPPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},
    {u8"jRK", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"jRKU", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"jRKB", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(70.0))},
    {u8"jRY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(80.0))},
    {u8"jRY1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(80.0))},
    {u8"jSTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jSTEELWEB", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jSHAPELISTNAME", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jSTANDARDSHAPESTEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"jH", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jB", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jT1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jT2", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jCOODINATEY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"jCOODINATEZ", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
};

const QStringList REGULATION::defaultBeamSrcSteelShape = {
    "", "WH", "WI", "WBX", "WP", "WT1", "WT2", "WT3", "WT4", "WC1", "WC2", "WC3", "WC4", "WPL", "WBR"
};

const QMap<QString, REGULATION> REGULATION::defaultWallRc = {
    {u8"NO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"LABEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FLOORFROM", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FLOORTO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"WALLTYPE", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"耐力壁"))},
    {u8"CONC", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"CONCTHICKNESS", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"STEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"STEELTHICKNESS", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"FINISHLOAD", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},

    {u8"BARARRANGEMENTTYPE", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"ダブル"))},
    {u8"vBARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"vBARPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},
    {u8"hBARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"hBARPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},

    {u8"vSMALLOPENINGBARNUM", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"vSMALLOPENINGBARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"hSMALLOPENINGBARNUM", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"hSMALLOPENINGBARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"dSMALLOPENINGBARNUM", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"dSMALLOPENINGBARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},

    {u8"vLARGEOPENINGBARNUM", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"vLARGEOPENINGBARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"hLARGEOPENINGBARNUM", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"hLARGEOPENINGBARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"dLARGEOPENINGBARNUM", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"dLARGEOPENINGBARPHI", REGULATION(TABLEDATATYPE::TB_STRING)}
};
const QStringList REGULATION::defaultWallRcType = {
    "", u8"耐力壁", u8"雑壁", u8"非構造モデル", u8"平板シェル要素", u8"平面応力要素"
};
const QStringList REGULATION::defaultWallRcBarArrangementType = {
    "", u8"シングル", u8"ダブル"
};

const QMap<QString, REGULATION> REGULATION::defaultWallS = {
    {u8"NO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"LABEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FLOORFROM", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FLOORTO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"WALLTYPE", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"耐力壁"))},
    {u8"STEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"STEELTHICKNESS", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"FINISHLOAD", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},

    {u8"vRIBPITCH", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"vRIBTYPE", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"vRIBTHICKNESS", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"vRIBBREADTH", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"hRIBPITCH", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"hRIBTYPE", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"hRIBTHICKNESS", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"hRIBBREADTH", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
};

const QStringList REGULATION::defaultWallSType = {
    "", u8"耐力壁", u8"雑壁", u8"非構造モデル", u8"平板シェル要素", u8"平面応力要素"
};

const QMap<QString, REGULATION> REGULATION::defaultWallUnderGround = {
    {u8"NO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"LABEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"CONC", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"CONCTHICKNESS", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"STEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"STEELTHICKNESS", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"FINISHLOAD", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"STANDARDBARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"STANDARDBARPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},

    {u8"vOUTERTOP_BARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"vOUTERTOP_BARPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},
    {u8"vOUTERMIDDLE_BARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"vOUTERMIDDLE_BARPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},
    {u8"vOUTERBOTTOM_BARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"vOUTERBOTTOM_BARPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},
    {u8"hOUTEREDGE_BARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"hOUTEREDGE_BARPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},
    {u8"hOUTERCENTER_BARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"hOUTERCENTER_BARPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},

    {u8"vINNERTOP_BARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"vINNERTOP_BARPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},
    {u8"vINNERMIDDLE_BARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"vINNERMIDDLE_BARPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},
    {u8"vINNERBOTTOM_BARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"vINNERBOTTOM_BARPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},
    {u8"hINNEREDGE_BARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"hINNEREDGE_BARPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},
    {u8"hINNERCENTER_BARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"hINNERCENTER_BARPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},
};

const QMap<QString, REGULATION> REGULATION::defaultSlab = {
    {u8"NO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"LABEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"SLABTYPE", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"非構造モデル"))},
    {u8"CONC", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"CONCTHICKNESS", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"STEEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"STEELTHICKNESS", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"FINISHLOAD", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"LISTLOADDIRECTION", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"STANDARDBARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"STANDARDBARPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},

    {u8"sUPPEREDGE_A_BARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"sUPPEREDGE_A_BARPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},
    {u8"sLOWEREDGE_A_BARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"sLOWEREDGE_A_BARPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},
    {u8"sUPPERCENTER_A_BARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"sUPPERCENTER_A_BARPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},
    {u8"sLOWERCENTER_A_BARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"sLOWERCENTER_A_BARPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},
    {u8"sUPPER_B_BARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"sUPPER_B_BARPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},
    {u8"sLOWER_B_BARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"sLOWER_B_BARPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},

    {u8"lUPPEREDGE_A_BARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"lUPPEREDGE_A_BARPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},
    {u8"lLOWEREDGE_A_BARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"lLOWEREDGE_A_BARPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},
    {u8"lUPPERCENTER_A_BARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"lUPPERCENTER_A_BARPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},
    {u8"lLOWERCENTER_A_BARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"lLOWERCENTER_A_BARPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},
    {u8"lUPPER_B_BARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"lUPPER_B_BARPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},
    {u8"lLOWER_B_BARPHI", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"lLOWER_B_BARPITCH", REGULATION(TABLEDATATYPE::TB_INT, QVariant(200))},
};

const QStringList REGULATION::defaultSlabType = {
    "", u8"非構造モデル", u8"平板シェル要素", u8"平面応力要素"
};

const QMap<QString, REGULATION> REGULATION::defaultBaseS = {
    {u8"NO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"LABEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"STANDARDTYPE", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"在来品"))},
    {u8"PRODUCTNAME", REGULATION(TABLEDATATYPE::TB_STRING)},

    {u8"B", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"D", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"T", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"BASEPLATEMATERIAL", REGULATION(TABLEDATATYPE::TB_STRING)},

    {u8"EDGEDISTANCEY1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"EDGEDISTANCEZ1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"BOLTNY1", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"BOLTNZ1", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"BOLTPHI", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"BOLTMATERIAL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"BOLTLENGTH", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))}
};

const QStringList REGULATION::defaultBaseSType = {
    "", u8"在来品"
};

const QMap<QString, REGULATION> REGULATION::defaultBaseSrc = {
    {u8"NO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"LABEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"B0", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"D0", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"CONC", REGULATION(TABLEDATATYPE::TB_STRING)},

    {u8"BASEPLATETYPE", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"長方形"))},
    {u8"B", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"D", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"T", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"SML", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},

    {u8"EDGEDISTANCEY1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"EDGEDISTANCEY2", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"EDGEDISTANCEZ1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"EDGEDISTANCEZ2", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"BOLTARRANGEMENTTYPE", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"長方形"))},
    {u8"BOLTNY1", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"BOLTNY2", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"BOLTNZ1", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"BOLTNZ2", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"BOLTPHI", REGULATION(TABLEDATATYPE::TB_INT, QVariant(0))},
    {u8"BOLTMATERIAL", REGULATION(TABLEDATATYPE::TB_STRING)},
};
const QStringList REGULATION::defaultBaseSrcBplShape = {
    "", u8"長方形", u8"八角形", u8"右隅切", u8"左隅切", u8"上隅切", u8"下隅切", u8"円形"
};

const QMap<QString, REGULATION> REGULATION::defaultIsolator = {
    {u8"NO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"LABEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"PRODUCTTYPE", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"PRODUCTNAME", REGULATION(TABLEDATATYPE::TB_STRING)},

    {u8"SHEARHYSTERESIS", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"hK1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"hK2", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"hK3", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"hFY1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"hFY2", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"AXIALHYSTERESIS", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"vK1", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"vK2", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"vK3", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"vFY1_PLUS", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"vFY2_PLUS", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},

    {u8"SELFWEIGHT", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"RENDERSHAPE", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"RENDERSIZED", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"RENDERSIZEH", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"SETLEVEL", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"DISPLACEMENT", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"SPRING", REGULATION(TABLEDATATYPE::TB_INT)},
    {u8"INFLECTION", REGULATION(TABLEDATATYPE::TB_DOUBLE)},

};
const QStringList REGULATION::defaultIsolatorType = {
    "", u8"直接入力"
};
const QStringList REGULATION::defaultIsolatorShearHysteresis = {
    "", u8"線形", u8"リバーシブルバイリニア", u8"バイリニア", u8"トリリニア"
};
const QStringList REGULATION::defaultIsolatorAxialHysteresis = {
    "", u8"線形", u8"引張リバーシブルバイリニア", u8"引張リバーシブルトリリニア"
};
const QStringList REGULATION::defaultIsolatorRender = {
    "", u8"形状A", u8"形状B", u8"形状C", u8"形状D", u8"形状E"
};

const QMap<QString, REGULATION> REGULATION::defaultDamper = {
    {u8"NO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"LABEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"PRODUCTTYPE", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"UNITS", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"PARAMETERS", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"SELFWEIGHT", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"VECTOR_X", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"VECTOR_Y", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"VECTOR_Z", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"NATURALPERIOD", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"DISPLACEMENT", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"MODEL_FLAG", REGULATION(TABLEDATATYPE::TB_BOOL)},
    {u8"RIGID_LENGTH", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"DAMPER_DIRECTION", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"TANALYSIS", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"FACTOR", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"FRAME_RIGIDITY", REGULATION(TABLEDATATYPE::TB_DOUBLE)}
};
const QStringList REGULATION::defaultDamperType = {
    "",
    u8" 1:線形ダンパー Kc=0",
    u8" 2:粘性制振壁 ADC旧式 Kc=0",
    u8" 3:2段階粘性減衰係数１ Kc=0",
    u8" 4:2段階粘性減衰係数２ Kc=0",
    u8" 5:線形ダンパー Kc≠0",
    u8" 6:粘性制振壁 ADC旧式 Kc≠0",
    u8" 7:2段階粘性減衰係数１ Kc≠0",
    u8" 8:2段階粘性減衰係数２ Kc≠0",
    u8" 9:GMS（一般化マクスウェルモデル）",
    u8"21:鋼材系バイリニア 剛性入力",
    u8"22:鋼材系バイリニア 構成入力",
    u8"23:鋼材系トリリニア 剛性入力",
    u8"24:鋼材系トリリニア 構成入力",
    u8"25:オイルダンパー",
    u8"26:粘性（CVα乗）ダンパー",
    u8"27:VEM　住友3M",
    u8"28:Hidaxダンパー　鹿島建設",
    u8"29:粘性制振壁　オイレス工業",
    u8"30:粘性制振壁　免制振デバイス",
    u8"31:付加質量",
    u8"32:SRI高硬度ダンパー 住友ゴム",
    u8"33:笠井モデル",
    u8"34:3段階線形粘性減衰係数"
};
const QList<QStringList> REGULATION::defaultDamperUnit = {
    /*  */QList<QString>{},
    /* 1*/QList<QString>{u8"Cd1(kNs/m)", u8"Kd(kN/m)"},
    /* 2*/QList<QString>{u8"Cd1(kNs/m)", u8"Kd(kN/m)", u8"d(m)"},
    /* 3*/QList<QString>{u8"Cd1(kN(s/m)^α1)", u8"α1", u8"Cd2(kN(s/m)^α2)", u8"α2", u8"Fdy(kN)", u8"Kd(kN/m)"},
    /* 4*/QList<QString>{u8"Cd1(kN(s/m)^α1)", u8"α1", u8"Cd2(kN(s/m)^α2)", u8"α2", u8"Fdy(kN)", u8"Kd(kN/m)"},
    /* 5*/QList<QString>{u8"Cd(kNs/m)", u8"Kd(kN/m)", u8"Kc(kN/m)"},
    /* 6*/QList<QString>{u8"Aw(cm2)", u8"d(cm)", u8"T(度)", u8"T1(sec)", u8"ek", u8"Kc(kN/cm)"},
    /* 7*/QList<QString>{u8"Cd1(kN(s/m)^α1)", u8"α1", u8"Cd2(kN(s/m)^α2)", u8"α2", u8"Fdy(kN)", u8"Kd(kN/m)", u8"Kc(kN/m)"},
    /* 8*/QList<QString>{u8"Cd1(kN(s/m)^α1)", u8"α1", u8"Cd2(kN(s/m)^α2)", u8"α2", u8"Fdy(kN)", u8"Kd(kN/m)", u8"Kc(kN/m)"},
    /* 9*/QList<QString>{u8"Cd1(kNs/cm)", u8"Kd1(kN/cm)", u8"Cd2(kNs/cm)", u8"Kd2(kN/cm)", u8"Cd3(kNs/cm)", u8"Kd3(kN/cm)", u8"Kc(kN/cm)"},
    /*21*/QList<QString>{u8"K1(kN/m)", u8"Fy(kN)", u8"K2(kN/m)", u8"Kc(kN/m)"},
    /*22*/QList<QString>{u8"E(kN/m2)", u8"Ap(m2)", u8"σy(kN/m2)", u8"α", u8"β", u8"Ep/E", u8"γ"},
    /*23*/QList<QString>{u8"K1(kN/m)", u8"Fy1(kN)", u8"K2(kN/m)", u8"Fy2(kN)", u8"K3(kN/m)", u8"Kc(kN/m)"},
    /*24*/QList<QString>{u8"E(kN/m2)", u8"Ap(m2)", u8"σy1(kN/m2)", u8"σy2(kN/m2)", u8"α", u8"β", u8"γ", u8"EP1/E", u8"Ep2/E"},
    /*25*/QList<QString>{u8"Cd1(KNs/m)", u8"Cd2/Cd1", u8"Kd(kN/m)", u8"δm(m)", u8"Fdy(kN)", u8"Kc(kN/m)"},
    /*26*/QList<QString>{u8"Cd1(kN(s/m)^α)", u8"α", u8"Kd(kN/m)", u8"δm(m)", u8"Kc(kN/m)"},
    /*27*/QList<QString>{u8"Ad(m2)", u8"d(m)", u8"δm(m)", u8"Kc(kN/m)"},
    /*28*/QList<QString>{u8"Cd1(kNs/m)", u8"Cd2(kNs/m)", u8"Cmin1(kN/m)", u8"Cmin2(kNs/m)", u8"Fdy(kN)" u8"Kc(kN/m)"},
    /*29*/QList<QString>{u8"S(m2)", u8"d(m)", u8"t(度)", u8"δm(m)", u8"Kc(kN/m)"},
    /*30*/QList<QString>{u8"Aw(m2)", u8"A=h/w", u8"d(m)", u8"δm(m)", u8"t(度)", u8"ek", u8"Kc(kN/m)"},
    /*31*/QList<QString>{u8"md(kNs^2/m)"},
    /*32*/QList<QString>{u8"A(m2)", u8"f", u8"t(m)", u8"T(度)", u8"CK", u8"CC", u8"Kc(kN/m)"},
    /*33*/QList<QString>{u8"塑性化部材種{100., 225., 400., 490.}", u8"Ap(m2)", u8"σy(N/mm2)", u8"Lp(m)", u8"Kc(kN/m)"},
    /*34*/QList<QString>{u8"Vd1(m/s)", u8"Fd1(kN)", u8"Vd2(m/s)," u8"Fd2(kN)", u8"Cd3(kN(s/m)^α1", u8"Kd(kN/m)", u8"Kc(kN/m)"},
};

const QMap<QString, REGULATION> REGULATION::defaultOpening = {
    {u8"NO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"LABEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"OPENINGTYPE", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"通常開口"))},
    {u8"LRBASE", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"LR", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"UDBASE", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"UD", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"POSITIONX", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"POSITIONY", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"WIDTH", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"HEIGHT", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"SLITL", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"SLITR", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"SLITB", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"SLITT", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"COMMENT", REGULATION(TABLEDATATYPE::TB_STRING)}
};
const QStringList REGULATION::defaultOpeningType = {
    "", u8"通常開口", u8"スリット", u8"解析開口"
};
const QStringList REGULATION::defaultOpeningLrBase = {
    "", u8"解析芯から", u8"内法から"
};
const QStringList REGULATION::defaultOpeningLr = {
    "", u8"左", u8"中央", u8"右"
};
const QStringList REGULATION::defaultOpeningUdBase = {
    "", u8"解析芯から", u8"内法から"
};
const QStringList REGULATION::defaultOpeningUd = {
    "", u8"上", u8"中央", u8"下"
};

const QMap<QString, REGULATION> REGULATION::defaultJointLoad = {
    {u8"NO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"NAME", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"TYPE", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FX", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"FY", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"FZ", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"MX", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"MY", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"MZ", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"COMMENT", REGULATION(TABLEDATATYPE::TB_STRING)},

};
const QStringList REGULATION::defaultLoadType = {
    "DL", "LL1", "LL2", "LL3", "LL4", "LLE"
};
const QMap<QString, REGULATION> REGULATION::defaultMemberLoad = {
    {u8"NO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"NAME", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"TYPE", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"COORDINATE", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"DIRECTION", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"WA", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"WB", REGULATION(TABLEDATATYPE::TB_DOUBLE)},
    {u8"COMMENT", REGULATION(TABLEDATATYPE::TB_STRING)},
};
const QStringList REGULATION::defaultMemberLoadCoordinate = {
    u8"全体座標系", u8"部材座標系"
};
const QStringList REGULATION::defaultMemberLoadDirection = {
    u8"X方向", u8"Y方向", u8"Z方向"
};

const QMap<QString, REGULATION> REGULATION::defaultSlabLoad = {
    {u8"NO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"NAME", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"DL", REGULATION(TABLEDATATYPE::TB_INT)},
    {u8"LL0", REGULATION(TABLEDATATYPE::TB_INT)},
    {u8"LL1", REGULATION(TABLEDATATYPE::TB_INT)},
    {u8"LL2", REGULATION(TABLEDATATYPE::TB_INT)},
    {u8"LL3", REGULATION(TABLEDATATYPE::TB_INT)},
    {u8"LL4", REGULATION(TABLEDATATYPE::TB_INT)},
    {u8"LLE", REGULATION(TABLEDATATYPE::TB_INT)},
    {u8"COMMENT", REGULATION(TABLEDATATYPE::TB_STRING)}
};

const QMap<QString, REGULATION> REGULATION::defaultJointTable = {
    {u8"NO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"X", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"Y", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"Z", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"FLOORS", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FRAMES", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"UUID", REGULATION(TABLEDATATYPE::TB_STRING)},
};
const QMap<QString, REGULATION> REGULATION::defaultMemberTable = {
    {u8"NO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"TYPE", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"NAME", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"WALLOPEN", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"JOINTS", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FLOORS", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FRAMES", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"ANGLE", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"IFACERULE", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"自動"))},
    {u8"IFACELEN", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"JFACERULE", REGULATION(TABLEDATATYPE::TB_STRING, QVariant(u8"自動"))},
    {u8"JFACELEN", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"SHIFTY", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"SHIFTZ", REGULATION(TABLEDATATYPE::TB_DOUBLE, QVariant(0.0))},
    {u8"UUID", REGULATION(TABLEDATATYPE::TB_STRING)},
};

const QStringList REGULATION::defaultMemberTableElementList = {
    u8"柱", u8"大梁", u8"ブレース", u8"小梁", u8"スラブ", u8"壁", u8"地下外壁", u8"制振要素", u8"免震要素"
};
const QStringList REGULATION::defaultMemberTableFaceRule = {
    u8"自動", u8"値指定"
};

const QMap<QString, REGULATION> REGULATION::defaultLoadTable = {
    {u8"NO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"TYPE", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"NAME", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"JOINTS", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FLOORS", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"FRAMES", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"UUID", REGULATION(TABLEDATATYPE::TB_STRING)}
};

const QStringList REGULATION::defaultLoadTableElementList = {
    u8"節点荷重", u8"部材荷重", u8"床荷重"
};

const QMap<QString, REGULATION> REGULATION::defaultIndivisualSettingType = {
    {u8"NO", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"LABEL", REGULATION(TABLEDATATYPE::TB_STRING)},
    {u8"LINECOLOR", REGULATION(TABLEDATATYPE::TB_STRING, QVariant("(none)"))},
    {u8"FILLCOLOR", REGULATION(TABLEDATATYPE::TB_STRING, QVariant("(none)"))},
    {u8"ALPHA", REGULATION(TABLEDATATYPE::TB_INT, QVariant(255))}
};

} // namespace post3dapp
