#include "abstracttext.h"
namespace post3dapp{
QPair<QPair<QString, QString>, QString> TextGirderCheck::write(const FixedData& fixedData) const{
    // CODE+PR511

    QString second;
    second.append(u8"XXX ZZ- ZZ  大梁の断面検討 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX [ 03/02/02 18:09:28 ] XXXXXXXXXX").append("\n");
    //Q_FOREACH(auto sec, UnifiedInputData::getInInstance()->getSectionValueList(DATATYPE::TPWALL)){
        second.append(u8"XXXXXXXXXXXXXXXX ( XXXXXX-FL XXXXXX-FRAME XXXXXX-XXXXXX (XXXXXX) XXXXXX-XXXXXX ) -S-   L=XX.XXX L0=XX.XXX(M)  FL=X.XXXX FR=X.XXXX(M)").append("\n");
        second.append(u8"       鉄骨              WH-1000X 201X 12X 20 (XXXXXXXX)    WH-1000X 201X 12X 20 (XXXXXXXX)    WH-1000X 201X 12X 20 (XXXXXXXX)").append("\n");
        second.append(u8"       幅厚比            B/F=XXX.X D/W=XXX.X                B/F=XXX.X D/W=XXX.X                B/F=XXX.X D/W=XXX.X").append("\n");
        second.append(u8"       lb,I*,Af(上)      lb=XXXXX. i*=XXX.XX Af=XXX.X       lb=XXXXX. i*=XXX.XX Af=XXX.X       lb=XXXXX. i*=XXX.XX Af=XXX.X").append("\n");
        second.append(u8"       lb,I*,Af(下)      lb=XXXXX. i*=XXX.XX Af=XXX.X       lb=XXXXX. i*=XXX.XX Af=XXX.X       lb=XXXXX. i*=XXX.XX Af=XXX.X").append("\n");
        second.append(u8"                        +----------- 左端 -----------+     +----------- 中央 -----------+     +----------- 右端 -----------+").append("\n");
        second.append(u8"  --- 曲げ軸力の検討 ---     PERM     TEMP     TEMP             PERM     TEMP     TEMP             PERM     TEMP     TEMP").append("\n");
        second.append(u8"   fb(N/mm2)(上端引張時) XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"   fb(N/mm2)(下端引張時) XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"       MLJ, MSJ (kNm)    XXXXXX.XUXXXXXX.XUXXXXXX.XU        XXXXXX.XUXXXXXX.XUXXXXXX.XU        XXXXXX.XUXXXXXX.XUXXXXXX.XU").append("\n");
        second.append(u8"       ML , MS  (kNm)    XXXXXX.XUXXXXXX.XUXXXXXX.XU        XXXXXX.XUXXXXXX.XUXXXXXX.XU        XXXXXX.XUXXXXXX.XUXXXXXX.XU").append("\n");
        second.append(u8"       MAL, MAS (kNm)    XXXXXX.XUXXXXXX.XUXXXXXX.XU        XXXXXX.XUXXXXXX.XUXXXXXX.XU        XXXXXX.XUXXXXXX.XUXXXXXX.XU").append("\n");
        second.append(u8"       検定比                 --- XXXXX.XX XXXXX.XX              --- XXXXX.XX XXXXX.XX              --- XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"       変動分検定比           --- XXXXX.XX XXXXX.XX              --- XXXXX.XX XXXXX.XX              --- XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"  ---- せん断の検討 ----").append("\n");
        second.append(u8"       QL , QL+QH (kN)   XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"       QL , QS    (kN)   XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"       QAL, QAS   (kN)   XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"       検定比                 --- XXXXX.XX XXXXX.XX              --- XXXXX.XX XXXXX.XX              --- XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"").append("\n");
    //}
    second.append(u8"XXX ZZ- ZZ  大梁の断面検討 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX [ 03/02/02 18:09:28 ] XXXXXXXXXX").append("\n");
    //Q_FOREACH(auto sec, UnifiedInputData::getInInstance()->getSectionValueList(DATATYPE::TPWALL)){
        second.append(u8"        B X D            XXXXX  X  XXXXX      (XXXXXXXX)    XXXXX  X  XXXXX      (XXXXXXXX)    XXXXX  X  XXXXX      (XXXXXXXX)").append("\n");
        second.append(u8"        上端主筋         2-D25( 75) 2-D25( 83) 2-D25( 91)   2-D25( 75) 2-D25( 83) 2-D25( 91)   2-D25( 75) 2-D25( 83) 2-D25( 91)").append("\n");
        second.append(u8"           at,d,j        at=XXX.XX(X.XX) d=XXXX j=XXXX      at=XXX.XX(X.XX) d=XXXX j=XXXX      at=XXX.XX(X.XX) d=XXXX j=XXXX").append("\n");
        second.append(u8"        下端主筋         2-D25( 75) 2-D25( 83) 2-D25( 91)   2-D25( 75) 2-D25( 83) 2-D25( 91)   2-D25( 75) 2-D25( 83) 2-D25( 91)").append("\n");
        second.append(u8"           at,d,j        at=XXX.XX(X.XX) d=XXXX j=XXXX      at=XXX.XX(X.XX) d=XXXX j=XXXX      at=XXX.XX(X.XX) d=XXXX j=XXXX").append("\n");
        second.append(u8"        あばら筋 pw(%)   2-D10-@180          pw= .23        2-D10-@180          pw= .23        2-D10-@180          pw= .23").append("\n");
        second.append(u8"                        +----------- 左端 -----------+     +----------- 中央 -----------+     +----------- 右端 -----------+").append("\n");
        second.append(u8"  --- 曲げ軸力の検討 ---     PERM     TEMP     TEMP             PERM     TEMP     TEMP             PERM     TEMP     TEMP").append("\n");
        second.append(u8"        MLJ,MSJ  (kNm)   XXXXXX.XUXXXXXX.XUXXXXXX.XU        XXXXXX.XUXXXXXX.XUXXXXXX.XU        XXXXXX.XUXXXXXX.XUXXXXXX.XU").append("\n");
        second.append(u8"        ML,MS    (kNm)   XXXXXX.XUXXXXXX.XUXXXXXX.XU        XXXXXX.XUXXXXXX.XUXXXXXX.XU        XXXXXX.XUXXXXXX.XUXXXXXX.XU").append("\n");
        second.append(u8"        MAL,MAS  (kNm)   XXXXXX.XUXXXXXX.XUXXXXXX.XU        XXXXXX.XUXXXXXX.XUXXXXXX.XU        XXXXXX.XUXXXXXX.XUXXXXXX.XU").append("\n");
        second.append(u8"        検定比                --- XXXXX.XX XXXXX.XX              --- XXXXX.XX XXXXX.XX              --- XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"        変動分検定比          --- XXXXX.XX XXXXX.XX              --- XXXXX.XX XXXXX.XX              --- XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"  ---- せん断の検討 ----").append("\n");
        second.append(u8"        α1, α2              ---  X.X X.X  X.X X.X              ---  X.X X.X  X.X X.X              ---  X.X X.X  X.X X.X").append("\n");
        second.append(u8"        α1*QH   +QL          --- XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"        α2*MY/L0+Q0          --- XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"        α               XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"        QL,  QL+QH  (kN) XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"        QL,  QS     (kN) XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"        QAL, QAS    (kN) XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"        QAL, QAS付着(kN) XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"        検定比           XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"        検定比  付着          --- XXXXX.XX XXXXX.XX              --- XXXXX.XX XXXXX.XX              --- XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"").append("\n");
    //}
    second.append(u8"XXX ZZ- ZZ  大梁の断面検討 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX [ 03/02/02 18:09:28 ] XXXXXXXXXX").append("\n");
    //Q_FOREACH(auto sec, UnifiedInputData::getInInstance()->getSectionValueList(DATATYPE::TPWALL)){
        second.append(u8"XXXXXXXXXXXXXXXX ( XXXXXX-FL XXXXXX-FRAME XXXXXX-XXXXXX (XXXXXX) XXXXXX-XXXXXX ) -SRC- L=XX.XXX L0=XX.XXX(M)  FL=X.XXXX FR=X.XXXX(M)").append("\n");
        second.append(u8"         B X D           XXXXX  X  XXXXX      (XXXXXXXX)    XXXXX  X  XXXXX      (XXXXXXXX)    XXXXX  X  XXXXX      (XXXXXXXX)").append("\n");
        second.append(u8"         上端主筋        2-D25( 75) 2-D25( 83) 2-D25( 91)   2-D25( 75) 2-D25( 83) 2-D25( 91)   2-D25( 75) 2-D25( 83) 2-D25( 91)").append("\n");
        second.append(u8"            at,d,j       at=XXX.XX(X.XX) d=XXXX j=XXXX      at=XXX.XX(X.XX) d=XXXX j=XXXX      at=XXX.XX(X.XX) d=XXXX j=XXXX").append("\n");
        second.append(u8"         下端主筋        2-D25( 75) 2-D25( 83) 2-D25( 91)   2-D25( 75) 2-D25( 83) 2-D25( 91)   2-D25( 75) 2-D25( 83) 2-D25( 91)").append("\n");
        second.append(u8"            at,d,j       at=XXX.XX(X.XX) d=XXXX j=XXXX      at=XXX.XX(X.XX) d=XXXX j=XXXX      at=XXX.XX(X.XX) d=XXXX j=XXXX").append("\n");
        second.append(u8"         あばら筋 pw(%)  2-D10-@180          pw= .23        2-D10-@180          pw= .23        2-D10-@180          pw= .23").append("\n");
        second.append(u8"         鉄骨            WH-1000X 201X 12X 20 (XXXXXXXX)    WH-1000X 201X 12X 20 (XXXXXXXX)    WH-1000X 201X 12X 20 (XXXXXXXX)").append("\n");
        second.append(u8"         幅厚比,B'       B/F=XX.X  D/W=XX.X  B'=XXXXX       B/F=XX.X  D/W=XX.X  B'=XXXXX       B/F=XX.X  D/W=XX.X  B'=XXXXX").append("\n");
        second.append(u8"                        +----------- 左端 -----------+     +----------- 中央 -----------+     +----------- 右端 -----------+").append("\n");
        second.append(u8"   --- 曲げ軸力の検討 --     PERM     TEMP     TEMP             PERM     TEMP     TEMP             PERM     TEMP     TEMP").append("\n");
        second.append(u8"         MLJ,MSJ   (kNm) XXXXXX.XUXXXXXX.XUXXXXXX.XU        XXXXXX.XUXXXXXX.XUXXXXXX.XU        XXXXXX.XUXXXXXX.XUXXXXXX.XU").append("\n");
        second.append(u8"         ML ,MS    (kNm) XXXXXX.XUXXXXXX.XUXXXXXX.XU        XXXXXX.XUXXXXXX.XUXXXXXX.XU        XXXXXX.XUXXXXXX.XUXXXXXX.XU").append("\n");
        second.append(u8"         MAL,MAS         XXXXXX.XUXXXXXX.XUXXXXXX.XU        XXXXXX.XUXXXXXX.XUXXXXXX.XU        XXXXXX.XUXXXXXX.XUXXXXXX.XU").append("\n");
        second.append(u8"         検定比               --- XXXXX.XX XXXXX.XX              --- XXXXX.XX XXXXX.XX              --- XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"         変動分検定比         --- XXXXX.XX XXXXX.XX              --- XXXXX.XX XXXXX.XX              --- XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"   ---- せん断の検討 ----").append("\n");
        second.append(u8"         QL,QL+QH  (kN)  XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"         rMAL,rMAS (kNm) XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"         sMAL,sMAS (kNm) XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"  [Root1,2] rMY/L0+(rQ0)      --- XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"  [Root1,2](rMY/MY)(Q0+2QH)   --- XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"         rQL,rQS   (kN)  XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"         rα             XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"         rQA1      (kN)  XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"         rQA2      (kN)  XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"         rQA       (kN)  XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"         検定比 RC       XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"         sQD       (kN)  XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"         sQA       (kN)  XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"         検定比 S        XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"").append("\n");
    //}
    second.append(u8"XXX ZZ- ZZ  大梁の断面検討 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX [ 03/02/02 18:09:28 ] XXXXXXXXXX").append("\n");
    //Q_FOREACH(auto sec, UnifiedInputData::getInInstance()->getSectionValueList(DATATYPE::TPWALL)){
        second.append(u8"XXXXXXXXXXXXXXXX ( XXXXXX-FL XXXXXX-FRAME XXXXXX-XXXXXX (XXXXXX) XXXXXX-XXXXXX ) -S-   L=XX.XXX L0=XX.XXX(M)  FL=X.XXXX FR=X.XXXX(M)").append("\n");
        second.append(u8"    鉄骨                 WH-1000X 201X 12X 20 (XXXXXXXX)    WH-1000X 201X 12X 20 (XXXXXXXX)    WH-1000X 201X 12X 20 (XXXXXXXX)").append("\n");
        second.append(u8"    幅厚比               B/F=XXX.X D/W=XXX.X                B/F=XXX.X D/W=XXX.X                B/F=XXX.X D/W=XXX.X").append("\n");
        second.append(u8"    lb,I*,Af(上)         lb=XXXXX. i*=XXX.XX Af=XXX.X       lb=XXXXX. i*=XXX.XX Af=XXX.X       lb=XXXXX. i*=XXX.XX Af=XXX.X").append("\n");
        second.append(u8"    lb,I*,Af(下)         lb=XXXXX. i*=XXX.XX Af=XXX.X       lb=XXXXX. i*=XXX.XX Af=XXX.X       lb=XXXXX. i*=XXX.XX Af=XXX.X").append("\n");
        second.append(u8"    圧縮検討用           ly=XXXXX. iy=XX.XX  fcL=XXX.X      ly=XXXXX. iy=XX.XX  fcL=XXX.X      ly=XXXXX. iy=XX.XX  fcL=XXX.X").append("\n");
        second.append(u8"     fc(N/mm2)           lz=XXXXX. iz=XX.XX  fcS=XXX.X      lz=XXXXX. iz=XX.XX  fcS=XXX.X      lz=XXXXX. iz=XX.XX  fcS=XXX.X").append("\n");
        second.append(u8"    曲げ検討用  長期     z=XXX.X, XXX.X y=XXX.X, XXX.X      z=XXX.X, XXX.X y=XXX.X, XXX.X      z=XXX.X, XXX.X y=XXX.X, XXX.X").append("\n");
        second.append(u8"     fb(N/mm2)  短期     z=XXX.X, XXX.X y=XXX.X, XXX.X      z=XXX.X, XXX.X y=XXX.X, XXX.X      z=XXX.X, XXX.X y=XXX.X, XXX.X").append("\n");
        second.append(u8"                         +----------- 左端 -----------+     +----------- 中央 -----------+     +----------- 右端 -----------+").append("\n");
        second.append(u8"  --- 曲げ軸力の検討 --- XXXXXXXX XXXXXXXX XXXXXXXX         XXXXXXXX XXXXXXXX XXXXXXXX         XXXXXXXX XXXXXXXX XXXXXXXX").append("\n");
        second.append(u8"    NL  ,NS   (kN)       XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"    MyL ,MyS  (kNm)      XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"    MzL ,MzS  (kNm)      XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"    NAL ,NAS  (kN)       XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"    MyAL,MyAS (kNm)      XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"    MzAL,MzAS (kNm)      XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"    検定比               XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"    変動分検定比              --- XXXXX.XX XXXXX.XX              --- XXXXX.XX XXXXX.XX              --- XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"  ---- せん断の検討 ----").append("\n");
        second.append(u8"    QyL ,QyS  (kN)       XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"    QzL ,QzS  (kN)       XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"    QyAL,QyAS (kN)       XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"    QzAL,QzAS (kN)       XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"    検定比               XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"").append("\n");
    //}
    second.append(u8"XXX ZZ- ZZ  大梁の断面検討 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX [ 03/02/02 18:09:28 ] XXXXXXXXXX").append("\n");
    //Q_FOREACH(auto sec, UnifiedInputData::getInInstance()->getSectionValueList(DATATYPE::TPWALL)){
        second.append(u8"XXXXXXXXXXXXXXXX ( XXXXXX-FL XXXXXX-FRAME XXXXXX-XXXXXX (XXXXXX) XXXXXX-XXXXXX ) -RC-  L=XX.XXX L0=XX.XXX(M)  FL=X.XXXX FR=X.XXXX(M)").append("\n");
        second.append(u8"        B X D            XXXXX  X  XXXXX      (XXXXXXXX)    XXXXX  X  XXXXX      (XXXXXXXX)    XXXXX  X  XXXXX      (XXXXXXXX)").append("\n");
        second.append(u8"        上端主筋         2-D25( 75) 2-D25( 83) 2-D25( 91)   2-D25( 75) 2-D25( 83) 2-D25( 91)   2-D25( 75) 2-D25( 83) 2-D25( 91)").append("\n");
        second.append(u8"           at,d,j        at=XXX.XX(X.XX) d=XXXX j=XXXX      at=XXX.XX(X.XX) d=XXXX j=XXXX      at=XXX.XX(X.XX) d=XXXX j=XXXX").append("\n");
        second.append(u8"        下端主筋         2-D25( 75) 2-D25( 83) 2-D25( 91)   2-D25( 75) 2-D25( 83) 2-D25( 91)   2-D25( 75) 2-D25( 83) 2-D25( 91)").append("\n");
        second.append(u8"           at,d,j        at=XXX.XX(X.XX) d=XXXX j=XXXX      at=XXX.XX(X.XX) d=XXXX j=XXXX      at=XXX.XX(X.XX) d=XXXX j=XXXX").append("\n");
        second.append(u8"        あばら筋 pw(%)   2-D10-@180          pw= .23        2-D10-@180          pw= .23        2-D10-@180          pw= .23").append("\n");
        second.append(u8"                        +----------- 左端 -----------+     +----------- 中央 -----------+     +----------- 右端 -----------+").append("\n");
        second.append(u8"  --- 曲げ軸力の検討 ---     PERM     TEMP     TEMP             PERM     TEMP     TEMP             PERM     TEMP     TEMP").append("\n");
        second.append(u8"    NL  ,NS   (kN)       XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"    MyL ,MyS  (kNm)      XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"    MzL ,MzS  (kNm)      XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"    NAL ,NAS  (kN)       XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"    MyAL,MyAS (kNm)      XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"    MzAL,MzAS (kNm)      XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"    検定比               XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"    変動分検定比              --- XXXXX.XX XXXXX.XX              --- XXXXX.XX XXXXX.XX              --- XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"  ---- せん断の検討 ----").append("\n");
        second.append(u8"   y軸 α1, α2               ---  X.X X.X  X.X X.X              ---  X.X X.X  X.X X.X              ---  X.X X.X  X.X X.X").append("\n");
        second.append(u8"       α1*QyH   +QyL(kN)     --- XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"       α2*MzY/L0+Qy0(kN)     --- XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"       α                XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"       QyL, QyL+QyH (kN) XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"       QyL, QyS     (kN) XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"       QyAL,QyAS    (kN) XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"       QyAL,QyAS付着(kN) XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"   z軸 α1, α2               ---  X.X X.X  X.X X.X              ---  X.X X.X  X.X X.X              ---  X.X X.X  X.X X.X").append("\n");
        second.append(u8"       α1*QzH   +QzL(kN)     --- XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"       α2*MyY/L0+Qz0(kN)     --- XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"       α                XXXXX.XX XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"       QzL, QzL+QzH (kN) XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"       QzL, QzS     (kN) XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"       QzAL,QzAS    (kN) XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"       QzAL,QzAS付着(kN) XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"       検定比            XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"       検定比  付着      XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"").append("\n");
    //}
    second.append(u8"XXX ZZ- ZZ  大梁の断面検討 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX [ 03/02/02 18:09:28 ] XXXXXXXXXX").append("\n");
    //Q_FOREACH(auto sec, UnifiedInputData::getInInstance()->getSectionValueList(DATATYPE::TPWALL)){
        second.append(u8"XXXXXXXXXXXXXXXX ( XXXXXX-FL XXXXXX-FRAME XXXXXX-XXXXXX (XXXXXX) XXXXXX-XXXXXX ) -SRC- L=XX.XXX L0=XX.XXX(M)  FL=X.XXXX FR=X.XXXX(M)").append("\n");
        second.append(u8"         B X D           XXXXX  X  XXXXX      (XXXXXXXX)    XXXXX  X  XXXXX      (XXXXXXXX)    XXXXX  X  XXXXX      (XXXXXXXX)").append("\n");
        second.append(u8"         上端主筋        2-D25( 75) 2-D25( 83) 2-D25( 91)   2-D25( 75) 2-D25( 83) 2-D25( 91)   2-D25( 75) 2-D25( 83) 2-D25( 91)").append("\n");
        second.append(u8"            at,d,j       at=XXX.XX(X.XX) d=XXXX j=XXXX      at=XXX.XX(X.XX) d=XXXX j=XXXX      at=XXX.XX(X.XX) d=XXXX j=XXXX").append("\n");
        second.append(u8"         下端主筋        2-D25( 75) 2-D25( 83) 2-D25( 91)   2-D25( 75) 2-D25( 83) 2-D25( 91)   2-D25( 75) 2-D25( 83) 2-D25( 91)").append("\n");
        second.append(u8"            at,d,j       at=XXX.XX(X.XX) d=XXXX j=XXXX      at=XXX.XX(X.XX) d=XXXX j=XXXX      at=XXX.XX(X.XX) d=XXXX j=XXXX").append("\n");
        second.append(u8"         あばら筋 pw(%)  2-D10-@180          pw= .23        2-D10-@180          pw= .23        2-D10-@180          pw= .23").append("\n");
        second.append(u8"         鉄骨            WH-1000X 201X 12X 20 (XXXXXXXX)    WH-1000X 201X 12X 20 (XXXXXXXX)    WH-1000X 201X 12X 20 (XXXXXXXX)").append("\n");
        second.append(u8"         幅厚比,B'       B/F=XX.X  D/W=XX.X  B'=XXXXX       B/F=XX.X  D/W=XX.X  B'=XXXXX       B/F=XX.X  D/W=XX.X  B'=XXXXX").append("\n");
        second.append(u8"                        +----------- 左端 -----------+     +----------- 中央 -----------+     +----------- 右端 -----------+").append("\n");
        second.append(u8"  --- 曲げ軸力の検討 ---     PERM     TEMP     TEMP             PERM     TEMP     TEMP             PERM     TEMP     TEMP").append("\n");
        second.append(u8"    NL  ,NS   (kN)       XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"    MyL ,MyS  (kNm)      XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"    MzL ,MzS  (kNm)      XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"    NAL ,NAS  (kN)       XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"    MyAL,MyAS (kNm)      XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"    MzAL,MzAS (kNm)      XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"    検定比               XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"    変動分検定比              --- XXXXX.XX XXXXX.XX              --- XXXXX.XX XXXXX.XX              --- XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"   ---- せん断の検討 ----").append("\n");
        second.append(u8"    y軸  QL,QL+QH  (kN)  XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"         rMzAL,rMzAS(kNm)XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"         sMzAL,sMzAS(kNm)XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"  [Root1,2] rMY/L0+(rQ0)      --- XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"  [Root1,2](rMY/MY)(Q0+2QH)   --- XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"         rQL,rQS   (kN)  XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"         rα             XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"         rQA1      (kN)  XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"         rQA2      (kN)  XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"         rQA       (kN)  XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"         sQD       (kN)  XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"         sQA       (kN)  XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"    z軸  QL,QL+QH  (kN)  XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"         rMyAL,rMyAS(kNm)XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"         sMyAL,sMyAS(kNm)XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"  [Root1,2] rMY/L0+(rQ0)      --- XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"  [Root1,2](rMY/MY)(Q0+2QH)   --- XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"         rQL,rQS   (kN)  XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"         rα             XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"         rQA1      (kN)  XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"         rQA2      (kN)  XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"         rQA       (kN)  XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"         sQD       (kN)  XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"         sQA       (kN)  XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"     検定比 RC           XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"     検定比 S            XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"").append("\n");
    //}
    return QPair<QPair<QString, QString>, QString>{QPair<QString, QString>{getCommand(), getJapanese()}, second};
}
} // namespace post3dapp
