#include "abstracttext.h"
namespace post3dapp{
QPair<QPair<QString, QString>, QString> TextColumnCheck::write(const FixedData& fixedData) const{
    //CODE+PR521

    QString second;
    second.append(u8"XXX ZZ- ZZ  柱の断面検討 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX [ 03/02/02 18:09:28 ] XXXXXXXXXX").append("\n");
    //Q_FOREACH(auto sec, UnifiedInputData::getInInstance()->getSectionValueList(DATATYPE::TPWALL)){
        second.append(u8"XXXXXXXXXXXXXXXX ( XXXXXX-FL XXXXXX-XXXXXX (XXXXXX) XXXXXX-XXXXXX ) -S-   L=XX.XXX(M) L0=XX.XXX(M)  FB=X.XXXX FT=X.XXXX(M) Lk=XX.XXX(M)").append("\n");
        second.append(u8"        y-鉄骨           WH-HHHHXBBBBXWWWXFFF (XXXXXXXX)  露出柱脚 XXXXXXXX   WH-HHHHXBBBBXWWWXFFF (XXXXXXXX)").append("\n");
        second.append(u8"          幅厚比         B/F=XX.X  D/W=XX.X               BPL XXXXxXXXXxXXX   B/F=XX.X  D/W=XX.X").append("\n");
        second.append(u8"          lb,I*,Af(R)    lb=XXXXX. I*=XXX.XX Af=XXX.X     CON XXXXXXXX        lb=XXXXX. I*=XXX.XX Af=XXX.X").append("\n");
        second.append(u8"          lb,I*,Af(L)    lb=XXXXX. I*=XXX.XX Af=XXX.X     ANB XXΦ XX x XX    lb=XXXXX. I*=XXX.XX Af=XXX.X").append("\n");
        second.append(u8"        z-鉄骨           WH-HHHHXBBBBXWWWXFFF (XXXXXXXX)                      WH-HHHHXBBBBXWWWXFFF (XXXXXXXX)").append("\n");
        second.append(u8"          幅厚比         B/F=XX.X  D/W=XX.X                                   B/F=XX.X  D/W=XX.X").append("\n");
        second.append(u8"          lb,I*,Af(R)    lb=XXXXX. I*=XXX.XX Af=XXX.X                         lb=XXXXX. I*=XXX.XX Af=XXX.X").append("\n");
        second.append(u8"          lb,I*,Af(L)    lb=XXXXX. I*=XXX.XX Af=XXX.X                         lb=XXXXX. I*=XXX.XX Af=XXX.X").append("\n");
        second.append(u8"        圧縮検討用       ly=XXXXX. iy=XX.XX                                   ly=XXXXX. iy=XX.XX").append("\n");
        second.append(u8"                         lz=XXXXX. iz=XX.XX                                   lz=XXXXX. iz=XX.XX").append("\n");
        second.append(u8"                        +-------------------- 柱脚 --------------------+     +-------------------- 柱頭 --------------------+").append("\n");
        second.append(u8"  --- 曲げ軸力の検討 ---     PERM     TEMP     TEMP     TEMP     TEMP             PERM     TEMP     TEMP     TEMP     TEMP").append("\n");
        second.append(u8"       ft       (N/mm2)  XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"       fc       (N/mm2)  XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"       NL,  NS     (kN)  XXXXXX.XTXXXXXX.XTXXXXXX.XTXXXXXX.XTXXXXXX.XT        XXXXXX.XTXXXXXX.XTXXXXXX.XTXXXXXX.XTXXXXXX.XT").append("\n");
        second.append(u8"       NAL, NAS    (kN)  XXXXXX.XTXXXXXX.XTXXXXXX.XTXXXXXX.XTXXXXXX.XT        XXXXXX.XTXXXXXX.XTXXXXXX.XTXXXXXX.XTXXXXXX.XT").append("\n");
        second.append(u8" z軸回 fb(R)    (N/mm2)  XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"       fb(L)    (N/mm2)  XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"       MzLJ, MzSJ  (kNm) XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8"       MzL , MzS   (kNm) XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8"       MzAL, MzAS  (kNm) XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8"      (MzAL0,MzAS0)(kNm) XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8" y軸回 fb(R)    (N/mm2)  XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"       fb(L)    (N/mm2)  XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"       MyLJ, MySJ  (kNm) XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8"       MyL , MyS   (kNm) XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8"       MyAL, MyAS  (kNm) XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8"      (MyAL0,MzAS0)(kNm) XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8"       検定比            XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"       変動分検定比           --- XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX              --- XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"      耐力壁分担割増係数      --- XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX              --- XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"  ---- せん断の検討 ----").append("\n");
        second.append(u8"   y軸 QyL , QyS   (kN)  XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"       QyAL, QyAS  (kN)  XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"      (QyAL0,QyAS0)(kN)  XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"   z軸 QzL , QzS   (kN)  XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"       QzAL, QzAS  (kN)  XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"      (QzAL0,QzAS0)(kN)  XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"       検定比            XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"").append("\n");
    //}
    second.append(u8"XXX ZZ- ZZ  柱の断面検討 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX [ 03/02/02 18:09:28 ] XXXXXXXXXX").append("\n");
    //Q_FOREACH(auto sec, UnifiedInputData::getInInstance()->getSectionValueList(DATATYPE::TPWALL)){
        second.append(u8"XXXXXXXXXXXXXXXX ( XXXXXX-FL XXXXXX-XXXXXX (XXXXXX) XXXXXX-XXXXXX ) -RC-  L=XX.XXX(M) L0=XX.XXX(M)  FB=X.XXXX FT=X.XXXX(M)").append("\n");
        second.append(u8"       B X D             XXXXX  X  XXXXX      (XXXXXXXX)                      XXXXX  X  XXXXX      (XXXXXXXX)").append("\n");
        second.append(u8"       Y- 鉄筋           4-D25( 75):Y1   2-D25( 91):Y1                        4-D25( 75):Y1   2-D25( 91):Y1").append("\n");
        second.append(u8"          at,d,j         at=XXX.XX(X.XX) d=XXXX j=XXXX                        at=XXX.XX(X.XX) d=XXXX j=XXXX").append("\n");
        second.append(u8"          帯筋 pw(%)     2-D13-@100          pw= .23                          2-D10-@180          pw= .23").append("\n");
        second.append(u8"       Z- 鉄筋           4-D25( 75):Y1   2-D25( 91):Y1                        4-D25( 75):Y1   2-D25( 91):Y1").append("\n");
        second.append(u8"          at,d,j         at=XXX.XX(X.XX) d=XXXX j=XXXX                        at=XXX.XX(X.XX) d=XXXX j=XXXX").append("\n");
        second.append(u8"          帯筋 pw(%)     2-D13-@100          pw= .23                          2-D10-@180          pw= .23").append("\n");
        second.append(u8"                        +-------------------- 柱脚 --------------------+     +-------------------- 柱頭 --------------------+").append("\n");
        second.append(u8"  --- 曲げ軸力の検討 ---     PERM     TEMP     TEMP     TEMP     TEMP             PERM     TEMP     TEMP     TEMP     TEMP").append("\n");
        second.append(u8"       NL,  NS     (kN)  XXXXXX.XTXXXXXX.XTXXXXXX.XTXXXXXX.XTXXXXXX.XT        XXXXXX.XTXXXXXX.XTXXXXXX.XTXXXXXX.XTXXXXXX.XT").append("\n");
        second.append(u8"       NAL, NAS    (kN)  XXXXXX.XTXXXXXX.XTXXXXXX.XTXXXXXX.XTXXXXXX.XT        XXXXXX.XTXXXXXX.XTXXXXXX.XTXXXXXX.XTXXXXXX.XT").append("\n");
        second.append(u8" z軸回 MzLJ, MzSJ  (kNm) XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8"       MzL , MzS   (kNm) XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8"       MzAL, MzAS  (kNm) XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8"      (MzAL0,MzAS0)(kNm) XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8" y軸回 MyLJ, MySJ  (kNm) XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8"       MyL , MyS   (kNm) XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8"       MyAL, MyAS  (kNm) XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8"      (MyAL0,MzAS0)(kNm) XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8"       検定比            XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"       変動分検定比           --- XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX              --- XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"      耐力壁分担割増係数      --- XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX              --- XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"  ---- せん断の検討 ----").append("\n");
        second.append(u8"   y軸 α1, α2               ---  X.X X.X  X.X X.X  X.X X.X  X.X X.X              ---  X.X X.X  X.X X.X  X.X X.X  X.X X.X").append("\n");
        second.append(u8"       α1*QyH   +QyL         --- XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"       α2*MzY/L0+Qy0         --- XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"       α                XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"       QyL, QyL+QyH (kN) XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"       QyL, QyS     (kN) XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"       QyAL,QyAS    (kN) XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"       QyAL,QyAS付着(kN) XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"   z軸 α1, α2               ---  X.X X.X  X.X X.X  X.X X.X  X.X X.X              ---  X.X X.X  X.X X.X  X.X X.X  X.X X.X").append("\n");
        second.append(u8"       α1*QzH   +QzL(kN)     --- XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"       α2*MyY/L0+Qz0(kN)     --- XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"       α                XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"       QzL, QzL+QzH (kN) XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"       QzL, QzS     (kN) XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"       QzAL,QzAS    (kN) XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"       QzAL,QzAS付着(kN) XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"       検定比            XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"       検定比   付着     XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"").append("\n");
    //}
    second.append(u8"XXX ZZ- ZZ  柱の断面検討 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX [ 03/02/02 18:09:28 ] XXXXXXXXXX").append("\n");
    //Q_FOREACH(auto sec, UnifiedInputData::getInInstance()->getSectionValueList(DATATYPE::TPWALL)){
        second.append(u8"XXXXXXXXXXXXXXXX ( XXXXXX-FL XXXXXX-XXXXXX (XXXXXX) XXXXXX-XXXXXX ) -SRC- L=XX.XXX(M) L0=XX.XXX(M)  FB=X.XXXX FT=X.XXXX(M) Lk=XX.XXX(M)").append("\n");
        second.append(u8"       B X D             XXXXX  X  XXXXX      (XXXXXXXX)                      XXXXX  X  XXXXX      (XXXXXXXX)").append("\n");
        second.append(u8"       Y- 鉄筋           4-D25( 75):Y1   2-D25( 91):Y1    非埋込柱脚          4-D25( 75):Y1   2-D25( 91):Y1    Lk/D=XXX.X 長柱").append("\n");
        second.append(u8"          at,d,j         at=XXX.XX(X.XX) d=XXXX j=XXXX     XXXXXXXX           at=XXX.XX(X.XX) d=XXXX j=XXXX").append("\n");
        second.append(u8"          帯筋 pw(%)     2-D13-@100          pw= .23       BPL XXXXxXXXXxXXX  2-D10-@180          pw= .23").append("\n");
        second.append(u8"          鉄骨           WH-1000X 201X 12X 20 (XXXXXXXX)   CON XXXXXXXX       WH-1000X 201X 12X 20 (XXXXXXXX)").append("\n");
        second.append(u8"          幅厚比,B'      B/F=XX.X  D/W=XX.X  B'=XXXXX      ANB XXΦ XX x XX   B/F=XX.X  D/W=XX.X  B'=XXXXX").append("\n");
        second.append(u8"       Z- 鉄筋           4-D25( 75):Y1   2-D25( 91):Y1                        4-D25( 75):Y1   2-D25( 91):Y1").append("\n");
        second.append(u8"          at,d,j         at=XXX.XX(X.XX) d=XXXX j=XXXX                        at=XXX.XX(X.XX) d=XXXX j=XXXX").append("\n");
        second.append(u8"          帯筋 pw(%)     2-D13-@100          pw= .23                          2-D10-@180          pw= .23").append("\n");
        second.append(u8"          鉄骨           WH-1000X 201X 12X 20 (XXXXXXXX)                      WH-1000X 201X 12X 20 (XXXXXXXX)").append("\n");
        second.append(u8"          幅厚比,B'      B/F=XX.X  D/W=XX.X  B'=XXXXX                         B/F=XX.X  D/W=XX.X  B'=XXXXX").append("\n");
        second.append(u8"                        +-------------------- 柱脚 --------------------+     +-------------------- 柱頭 --------------------+").append("\n");
        second.append(u8"  --- 曲げ軸力の検討 ---     PERM     TEMP     TEMP     TEMP     TEMP             PERM     TEMP     TEMP     TEMP     TEMP").append("\n");
        second.append(u8"  軸力 NL,  NS     (kN)  XXXXXX.XTXXXXXX.XTXXXXXX.XTXXXXXX.XTXXXXXX.XT        XXXXXX.XTXXXXXX.XTXXXXXX.XTXXXXXX.XTXXXXXX.XT").append("\n");
        second.append(u8"       NAL, NAS    (kN)  XXXXXX.XTXXXXXX.XTXXXXXX.XTXXXXXX.XTXXXXXX.XT        XXXXXX.XTXXXXXX.XTXXXXXX.XTXXXXXX.XTXXXXXX.XT").append("\n");
        second.append(u8" z軸回 MzLJ, MzSJ  (kNm) XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8"       MzL , MzS   (kNm) XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8"       MzAL, MzAS  (kNm) XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8"    ( MzAL0, MzAS0)(kNm) XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8" y軸回 MyLJ, MySJ  (kNm) XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8"       MyL , MyS   (kNm) XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8"       MyAL, MyAS  (kNm) XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8"    ( MyAL0, MyAS0)(kNm) XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8"      検定比             XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"      変動分検定比            --- XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX              --- XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"      耐力壁分担割増係数      --- XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX              --- XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"  ---- せん断の検討 ----").append("\n");
        second.append(u8"  y軸 1+β               XXXXX.XX      ---      ---      ---      ---         XXXXX.XX      ---      ---      ---      ---").append("\n");
        second.append(u8"      α1*QyH   +QyL(kN)      --- XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"      α2*MzY/L0+Qy0(kN)      --- XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"    ( α' ), α         (XXXXX.XX)XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX        (XXXXX.XX)XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"    (rQyAL),rQyAS1 (kN) (XXXXXX.X)XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X        (XXXXXX.X)XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"            rQyAS2 (kN)       --- XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"      QyL, QyL+QyH (kN)  XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"      rMzAL,rMzAS (kNm)  XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8"      sMzAL,sMzAS (kNm)  XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8"      rQyL , rQyS  (kN)  XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"      rQyAL, rQyAS (kN)  XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"    (rQyAL0,rQyAS0)(kN)  XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"     sQyL , sQyS   (kN)       --- XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"     sQyAL, sQyAS  (kN)       --- XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"    (sQyAL0,sQyAS0)(kN)       --- XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"  z軸 1+β               XXXXX.XX      ---      ---      ---      ---         XXXXX.XX      ---      ---      ---      ---").append("\n");
        second.append(u8"      α1*QzH   +QzL(kN)      --- XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"      α2*MyY/L0+Qz0(kN)      --- XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"    ( α' ), α         (XXXXX.XX)XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX        (XXXXX.XX)XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"    (rQzAL),rQyAS1 (kN) (XXXXXX.X)XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X        (XXXXXX.X)XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"            rQyAS2 (kN)       --- XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"      QzL ,QzL+QzH (kN)  XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"      rMyAL,rMyAS (kNm)  XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8"      sMyAL,sMyAS (kNm)  XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8"     rQzL , rQzS   (kN)  XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"     rQzAL, rQzAS  (kN)  XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"    (rQzAL0,rQzAS0)(kN)  XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"     sQzL , sQzS   (kN)       --- XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"     sQzAL, sQzAS  (kN)       --- XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"    (sQzAL0,sQzAS0)(kN)       --- XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X              --- XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"     検定比 RC           XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"     検定比 S                 --- XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX              --- XXXXX.XX XXXXX.XX XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"").append("\n");
    //}
    second.append(u8"XXX ZZ- ZZ  柱の断面検討 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX [ 03/02/02 18:09:28 ] XXXXXXXXXX").append("\n");
    //Q_FOREACH(auto sec, UnifiedInputData::getInInstance()->getSectionValueList(DATATYPE::TPWALL)){
        second.append(u8"XXXXXXXXXXXXXXXX ( XXXXXX-FL XXXXXX-XXXXXX (XXXXXX) XXXXXX-XXXXXX ) -CFT- L=XX.XXX(M) L0=XX.XXX(M)  FB=X.XXXX FT=X.XXXX(M) Lk=XX.XXX(M)").append("\n");
        second.append(u8"       鉄骨              P -1000X 20          (XXXXXXXX)  露出柱脚 XXXXXXXX   P -1000X201          (XXXXXXXX)").append("\n");
        second.append(u8"       D/T,As,σy        D/T=XX.X  As=XXX.X σy=XXXXX.X   BPL XXXXxXXXXxXXX   D/T=XX.X  AS=XXX.X σy=XXXXX.X  lk/D=XXX.X 長柱").append("\n");
        second.append(u8"       コンクリート      Fc =XXXX.X Ac=XXXX.X (XXXXXXXX)  CON XXXXXXXX        Fc =XXXX.X Ac=XXXX.X (XXXXXXXX) h0/D=XXX.X≦6").append("\n");
        second.append(u8"       拘束効果          cfc=XXXX.X cfc(短期)=XXXX.X      ANB XXΦ XX x XX    cfc=XXXX.X cfc(短期)=XXXX.X").append("\n");
        second.append(u8"                        +------------------ BOTTOM --------------------+     +-------------------- TOP ---------------------+").append("\n");
        second.append(u8"  --- 曲げ軸力の検討 ---     PERM     TEMP     TEMP     TEMP     TEMP             PERM     TEMP     TEMP     TEMP     TEMP").append("\n");
        second.append(u8"  軸力 NL,  NS     (kN)  XXXXXX.XTXXXXXX.XTXXXXXX.XTXXXXXX.XTXXXXXX.XT        XXXXXX.XTXXXXXX.XTXXXXXX.XTXXXXXX.XTXXXXXX.XT").append("\n");
        second.append(u8"       NAL, NAS    (kN)  XXXXXX.XTXXXXXX.XTXXXXXX.XTXXXXXX.XTXXXXXX.XT        XXXXXX.XTXXXXXX.XTXXXXXX.XTXXXXXX.XTXXXXXX.XT").append("\n");
        second.append(u8" z軸回 MzLJ, MzSJ  (kNm) XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8"       MzL , MzS   (kNm) XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8"       MzAL, MzAS  (kNm) XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8"    ( MzAL0, MzAS0)(kNm) XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8" y軸回 MyLJ, MySJ  (kNm) XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8"       MyL , MyS   (kNm) XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8"       MyAL, MyAS  (kNm) XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8"    ( MyAL0, MyAS0)(kNm) XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR        XXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XRXXXXXX.XR").append("\n");
        second.append(u8"   検定比                XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"   変動分検定比               --- XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX              --- XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"   耐力壁分担割増係数         --- XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX              --- XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX").append("\n");
        second.append(u8"  ---- せん断の検討 ----").append("\n");
        second.append(u8"  y軸  QyL ,  QyS  (kN)  XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"      sQyAL, sQyAS (kN)  XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"    (sQyAL0,sQyAS0)(kN)  XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"  z軸  QzL ,  QzS  (kN)  XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"      sQzAL, sQzAS (kN)  XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"    (sQzAL0,sQzAS0)(kN)  XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X         XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"  検定比                 XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX XXXXX.XX         XXXXX.XX XXXXX.XX XXXXX.XX XXXXXX.X XXXXXX.X").append("\n");
        second.append(u8"").append("\n");
    //}
    return QPair<QPair<QString, QString>, QString>{QPair<QString, QString>{getCommand(), getJapanese()}, second};
}
} // namespace post3dapp
